// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfbnlouycrkyfrobrpcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYm5sb3V5Y3JreWZyb2JycGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MjM1MzUsImV4cCI6MjA1MTA5OTUzNX0.WGunSOtrXJjBZx-XOZNho0h9H6ZaQFcQU4_qC83wFzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);